### ISSUE TITLE
Name, Email and Avatar in idToken not available

### ISSUE THREAD

**Issue by ramsaylanier** [LawJolla/prisma-auth0-example#1]
Thanks for this great boilerplate. I've used it as a starting point for a current project. I've currently got everything working, but for some reason when I `createPrismaUser` the idToken that is passed in does not have the users name, email, or picture. Is that something I have to setup in Auth0?

**Comment by ramsaylanier** [comment]
heh I just figured out I was missing it in the scope of the auth0 property of the Auth class.

**Comment by LawJolla** [comment]
Thanks for the nice words!   Glad you got it figured out.  Specifying the scope returns different information, as you mentioned.  And there's different info from different social providers, so there may be quite a bit of logic stuck into `createPrismaUser` to massage all of the different permutations.

If you have any other suggestions or improvements, please let me know!
