### ISSUE TITLE
How to run authenticated query or mutation in GraphQL Playground?

### ISSUE THREAD

**Issue by sakhmedbayev** [LawJolla/prisma-auth0-example#3]
Hi @LawJolla! Thanks for the awesome example. Very cool!

I cannot understand how to run authenticated query or mutation in GraphQL Playground?

I tried to set `Authorization1` header in the playground in the following way:

```
{
  "Authorization" : {
    "Bearer": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJERTBNamN3UkRVNFFrTTNOakkyTkRRNE9EbERPRFZGTmp..."
  }
}
```

So far it did not work. What else needs to be done to make it work?

**Comment by LawJolla** [comment]
Hi @sakhmedbayev , 

Thanks for checking it out!  

The format is: 

```
{
  "Authorization": "Bearer <JWT>"
}
```
