### ISSUE TITLE
Owner field label must be user

### ISSUE THREAD

**Issue by picosam** [LawJolla/prisma-auth0-example#4]
Hello!
`const isRequestingUserAlsoOwner = ({ ctx, userId, type, typeId }) => ctx.db.exists[type]({ id: typeId, user: { id: userId } });`
Am I right to assume that the above assumes that any type that is linked to the `User` type to denote ownership must label the field as `user` and not, for instance, `owner`?

**Comment by LawJolla** [comment]
You're correct.  I thought several times "I should make a comment to make that assumption explicit" but, as you can see, I failed on that one.  I'll add comments on the next iteration!

But whatever your node structure, it should be malleable enough to make a different `isOwner` function.

**Comment by picosam** [comment]
Thank you! I was actually wondering if we can make it dynamic somehow... that is to say, the same `isOwner` function.

**Comment by LawJolla** [comment]
Can you expand further?  I'm not totally following.  What would you like it to do?

**Comment by picosam** [comment]
I'm imagining this:
`directive @isOwner(type: String, field: String) on QUERY | MUTATION`

Where it would be used as follows:
```
...
publish(id: ID!): Post @isOwner(type: "Post", field: "author")
...
```

The idea is to make this word for the following type:
```
type Post {
  ...
  author: User @relation(name: "UserPosts")
}
```

**Comment by LawJolla** [comment]
So the permission is you only want to show author if User owns the Post?

**Comment by picosam** [comment]
Actually, I want to be free to define the ownership field as anything (not just `user`) on any type. If I understood correctly, the directive as it is now would fail for the `Post` type above because there is no field named `user` on the type `Post`; it's named `author` instead.

**Comment by LawJolla** [comment]
I think what you're looking for is... 

```
...
 publish(id: ID!): Post @isOwner(type: "Post")
...

type Post {
  ...
  author: User @isOwner(type: "User")
}
```

**Comment by picosam** [comment]
But then wouldn't this fail:
`const isRequestingUserAlsoOwner = ({ ctx, userId, type, typeId }) => ctx.db.exists[type]({ id: typeId, user: { id: userId } });`
Since it's looking for `user` in the `exists` function, not `author`?
I'm very sorry I'm insisting, there must be something I don't get!

**Comment by LawJolla** [comment]
Are you on the most recent version?  a `type: "User"` never hits that function.  It's a little hacky, but `User` is a special case, so it should be ok.

```
  isOwner: async (next, source, { type }, ctx) => {
    const { id: typeId } =
      source && source.id
        ? source
        : ctx.request.body.variables ? ctx.request.body.variables : {id: null}
    const { id: userId } = isLoggedIn(ctx)
    const isOwner =
      type === `User`
        ? userId === typeId
        : await isRequestingUserAlsoOwner({ ctx, userId, type, typeId })
    if (isOwner) {
      return next()
    }
    throw new Error(`Unauthorized, must be owner`)
  },
```
